'use strict';
const express=require('express');
const { apiRequest }=require('../remoteDb.cjs');
const router=express.Router();
router.get('/',async(req,res,next)=>{try{res.json(await apiRequest('/api/orders'));}catch(e){next(e)}});
router.get('/unpaid',async(req,res,next)=>{try{res.json(await apiRequest('/api/orders?unpaid=1'));}catch(e){next(e)}});
router.get('/since/:iso',async(req,res,next)=>{try{res.json(await apiRequest(`/api/orders?since=${encodeURIComponent(decodeURIComponent(req.params.iso))}`));}catch(e){next(e)}});
router.post('/',async(req,res,next)=>{try{res.json(await apiRequest('/api/orders',{method:'POST',body:req.body}));}catch(e){next(e)}});
router.patch('/:id/paid',async(req,res,next)=>{try{res.json(await apiRequest(`/api/orders/${req.params.id}/paid`,{method:'PATCH',body:req.body}));}catch(e){next(e)}});
module.exports=router;
